In [ ]:
# 04 – Batting Role Analysis

Purpose:
- Identify batting roles using engineered features
- Classify players as Openers, Middle Order, Finishers

Input:
- data/processed/batting_features_final_v2.csv

Outputs:
- data/processed/openers.csv
- data/processed/middle_order.csv
- data/processed/finishers.csv

In [2]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

from config import *
import pandas as pd

In [3]:
batting = pd.read_csv(
    PROCESSED_DIR / "batting_features_final_v2.csv"
)

print(batting.shape)
batting.head()

(704, 16)

,batsman,runs,balls,dismissals,strike_rate,average,matches_played,Death,Middle,Powerplay,boundary_pct,dot_ball_pct,dismissal_rate,avg_pp_balls_per_match,avg_middle_balls_per_match,avg_death_balls_per_match
0,A Ashish Reddy,280,193,15,145.077720,18.666667,23,146.575342,148.780488,83.333333,55.000000,30.051813,12.866667,0.260870,1.782609,6.347826
1,A Badoni,963,693,36,138.961039,26.750000,46,164.217252,126.126126,61.702128,53.997923,31.024531,19.250000,1.021739,7.239130,6.804348
2,A Chandila,4,7,1,57.142857,4.000000,2,57.142857,NaN,NaN,0.000000,42.857143,7.000000,0.000000,0.000000,3.500000
3,A Chopra,53,71,5,74.647887,10.600000,6,50.000000,83.333333,69.230769,52.830189,57.746479,14.200000,6.500000,5.000000,0.333333
4,A Choudhary,25,20,2,125.000000,12.500000,3,125.000000,NaN,NaN,40.000000,20.000000,10.000000,0.000000,0.000000,6.666667

In [4]:
openers = batting[
    (batting["matches_played"] >= 50) &
    (batting["balls"] >= 300) &
    (batting["strike_rate"] >= 135) &
    (batting["average"] >= 28) &
    (batting["Powerplay"] >= 140) &
    (batting["avg_pp_balls_per_match"] >= 6)
].copy()

openers = openers.sort_values(
    "matches_played", ascending=False
)

openers.head()

,batsman,runs,balls,dismissals,strike_rate,average,matches_played,Death,Middle,Powerplay,boundary_pct,dot_ball_pct,dismissal_rate,avg_pp_balls_per_match,avg_middle_balls_per_match,avg_death_balls_per_match
248,JC Buttler,4121,2749,106,149.909058,38.877358,119,198.097826,144.406780,140.549542,66.537248,36.485995,25.933962,10.092437,9.915966,3.092437
693,YBK Jaiswal,2166,1412,62,153.399433,34.935484,66,209.523810,138.339921,159.490741,73.314866,39.305949,22.774194,13.090909,7.666667,0.636364
263,JM Bairstow,1674,1142,50,146.584939,33.480000,52,136.363636,141.163793,151.524880,67.861410,38.704028,22.840000,11.980769,8.923077,1.057692

In [5]:
middle_order = batting[
    (batting["matches_played"] >= 80) &
    (batting["balls"] >= 600) &
    (batting["strike_rate"] >= 120) &
    (batting["average"] >= 30) &
    (batting["Middle"] >= 120) &
    (batting["avg_middle_balls_per_match"] >= 6) &
    (batting["avg_middle_balls_per_match"] >
     batting["avg_pp_balls_per_match"])
].copy()

middle_order = middle_order.sort_values(
    "matches_played", ascending=False
)

middle_order.head()

,batsman,runs,balls,dismissals,strike_rate,average,matches_played,Death,Middle,Powerplay,boundary_pct,dot_ball_pct,dismissal_rate,avg_pp_balls_per_match,avg_middle_balls_per_match,avg_death_balls_per_match
659,V Kohli,8671,6505,231,133.297463,37.536797,259,187.671233,125.139492,126.292407,55.910506,32.959262,28.160173,9.559846,12.455598,3.100386
570,SK Raina,5536,4025,168,137.540373,32.952381,200,172.552783,131.551945,133.905579,58.670520,33.142857,23.958333,5.825000,11.695000,2.605000
597,SV Samson,4704,3368,151,139.667458,31.152318,171,191.646192,137.587885,124.100719,60.161565,34.412114,22.304636,6.502924,10.812865,2.380117
31,AB de Villiers,5181,3400,125,152.382353,41.448000,170,225.331725,131.425652,120.684039,61.262305,30.558824,27.200000,3.611765,11.511765,4.876471
554,SA Yadav,4311,2889,123,149.221184,35.048780,151,182.039911,144.293785,140.119760,65.506843,33.852544,23.487805,4.423841,11.721854,2.986755

In [6]:
finishers = batting[
    (batting["matches_played"] >= 80) &
    (batting["balls"] >= 400) &
    (batting["strike_rate"] >= 140) &
    (batting["Death"] >= 150) &
    (batting["avg_death_balls_per_match"] >= 3)
].copy()

finishers = finishers.sort_values(
    "matches_played", ascending=False
)

finishers.head()

,batsman,runs,balls,dismissals,strike_rate,average,matches_played,Death,Middle,Powerplay,boundary_pct,dot_ball_pct,dismissal_rate,avg_pp_balls_per_match,avg_middle_balls_per_match,avg_death_balls_per_match
31,AB de Villiers,5181,3400,125,152.382353,41.448000,170,225.331725,131.425652,120.684039,61.262305,30.558824,27.200000,3.611765,11.511765,4.876471
285,KA Pollard,3437,2315,129,148.466523,26.643411,168,172.203390,124.493554,108.163265,64.823974,36.371490,17.945736,0.291667,6.464286,7.023810
694,YK Pathan,3222,2233,111,144.290193,29.027027,153,161.781609,134.080371,148.559671,62.631906,34.975369,20.117117,1.588235,8.457516,4.549020
218,HH Pandya,2758,1867,99,147.723621,27.858586,140,172.705314,133.679354,98.255814,62.654097,33.261918,18.858586,1.228571,6.192857,5.914286
514,RR Pant,3566,2408,107,148.089701,33.327103,123,203.252033,136.568123,122.500000,64.610208,34.094684,22.504673,2.926829,12.650407,4.000000

In [7]:
openers.to_csv(
    PROCESSED_DIR / "openers.csv",
    index=False
)

In [8]:
middle_order.to_csv(
    PROCESSED_DIR / "middle_order.csv",
    index=False
)

In [9]:
finishers.to_csv(
    PROCESSED_DIR / "finishers.csv",
    index=False
)